global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8070']

  - job_name: 'backend'
    static_configs:
      - targets: ['cv-challenge01-backend-1:8000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['cv-challenge01-frontend-1:5173']
