global:
  scrape_interval: 15s # How often to scrape targets by default.
  evaluation_interval: 15s # How often to evaluate rules.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']

  - job_name: 'application-backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'application-frontend'
    static_configs:
      - targets: ['frontend:5173']

  - job_name: 'adminer'
    static_configs:
      - targets: ['adminer:8080']
